apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fd-f1-preprocess
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/fd-f1-preprocess:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fd-f2-backbone
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/fd-f2-backbone:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fd-f3-classifier
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/fd-f3-classifier:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fd-f4-bbox
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/fd-f4-bbox:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fd-f5-landmark
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/fd-f5-landmark:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fd-f6-merge
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/fd-f6-merge:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
