apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ocr-f1-split
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/ocr-f1-split:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: F2_URL
              value: "http://ocr-f2-worker.default.svc.cluster.local/"
            - name: REDIS_HOST
              value: "redis.default.svc.cluster.local"
          resources:
            limits:
              cpu: "2"
              memory: "256Mi"
            requests:
              cpu: "500m"
              memory: "128Mi"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ocr-f2-worker
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/ocr-f2-worker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: F3_URL
              value: "http://ocr-f3-merge.default.svc.cluster.local/"
            - name: REDIS_HOST
              value: "redis.default.svc.cluster.local"
          resources:
            limits:
              cpu: "2"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "128Mi"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ocr-f3-merge
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/ocr-f3-merge:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: F4_URL
              value: "http://ocr-f4-extract.default.svc.cluster.local/"
            - name: REDIS_HOST
              value: "redis.default.svc.cluster.local"
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ocr-f4-extract
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/ocr-f4-extract:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis.default.svc.cluster.local"
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"

