apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mc-f1-request
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/mc-f1-request:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: F2_URL
              value: "http://mc-f2-scenario.default.svc.cluster.local/"
            - name: REDIS_HOST
              value: "redis.default.svc.cluster.local"
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mc-f2-scenario
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/mc-f2-scenario:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: F3_URL
              value: "http://mc-f3-worker.default.svc.cluster.local/"
            - name: REDIS_HOST
              value: "redis.default.svc.cluster.local"
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mc-f3-worker
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "20"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/mc-f3-worker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: F4_URL
              value: "http://mc-f4-aggregate.default.svc.cluster.local/"
            - name: REDIS_HOST
              value: "redis.default.svc.cluster.local"
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mc-f4-aggregate
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/mc-f4-aggregate:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis.default.svc.cluster.local"
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"

