apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: qr-f1-gen
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: 172.0.0.0:5000/qr-f1-gen:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
